### ISSUE TITLE
Service invocation using gRPC isn't working.

### ISSUE THREAD

**Issue by joramnv** [dapr/js-sdk#221]
## Expected Behavior

I expect to use the invoke method to make a successful call to another service implementing a gRPC server and exposing it using Dapr. 

## Actual Behavior

When I use the js-sdk invoke method, it always results in `Error: 1 CANCELLED: stream terminated by RST_STREAM with error code: CANCEL`.
Whole log:
```
[Dapr-JS][gRPC] Opening connection to 127.0.0.1:50002
Error: 1 CANCELLED: stream terminated by RST_STREAM with error code: CANCEL
    at Object.callErrorFromStatus (/Users/joram/projects/ami-api-gateway/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/joram/projects/ami-api-gateway/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/Users/joram/projects/ami-api-gateway/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/Users/joram/projects/ami-api-gateway/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/joram/projects/ami-api-gateway/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 1,
  details: 'stream terminated by RST_STREAM with error code: CANCEL',
  metadata: Metadata {
    internalRepr: Map(2) { 'traceparent' => [Array], 'grpc-trace-bin' => [Array] },
    options: {}
  }
}
```
At the receiving service, a warning appears in the logs:
```
Mar 22, 2022 7:49:39 PM io.grpc.internal.ServerCallImpl internalClose
WARNING: Cancelling the stream with status Status{code=INTERNAL, description=Completed without a response, cause=null}
Exception in thread "grpc-default-executor-15" com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:107)
```

## Steps to Reproduce the Problem

- Run the service which implements the gRPC server. (This is the specific service I am using: https://github.com/joramnv/ktor_demo_app_a)
    - Start the sidecar first: `dapr run --components-path ./secrets --app-id app-a --app-port 48123 --app-protocol grpc --dapr-http-port 3500 --dapr-grpc-port 50001`
    - Start the app: `gradlew run` / `./gradlew run`

- Run a sidecar for the Node app: `dapr run --app-id hello-world --app-protocol grpc --dapr-grpc-port 50002`
- Run the following saved as js file by executing: `node -e 'require("./{file_name}")'`:
```
const { DaprClient, DaprServer, CommunicationProtocolEnum, HttpMethod } = require('dapr-client');

const daprHost = "127.0.0.1"; // Dapr Sidecar Host
const daprPort = "50002"; // Dapr Sidecar Port of this Example Server

const client = new DaprClient(daprHost, daprPort, CommunicationProtocolEnum.GRPC);

async function start() {
    const res = await client.invoker.invoke("app-a", "whoIs", HttpMethod.POST, { requestFrom: "hello world" });
}

start().catch(e => console.error(e));
```

**Comment by amulyavarote** [comment]
Hi! I tried service invocation grpc functionality using the sample examples we have in the js-sdk repo. It works perfectly fine. I request you to take a look or debug the application code once if all the params to the invoke method are passed properly.

**Comment by joramnv** [comment]
I had to read back the conversation ( https://discord.com/channels/778680217417809931/864937433387499540/955863602496155708 ) which lead to creating this issue ticket.

I believe the problem might be that I was under the impression that gRPC implied support for Protobuf, but it seems that is not the case. (Java SDK does support Protobuf messages.)

I guess this could be considered a bug or not depending on if you think Protobuf should be supported or not.
