### ISSUE TITLE
Fix Dapr Bot

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#239]
Dapr bot has been failing since #210 with the following error:

```js
/home/runner/work/js-sdk/js-sdk/.github/scripts/dapr_bot.js:159
Error: Unhandled error: SyntaxError: Unexpected token 'export'
export default async ({ github, context }) => {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:[10](https://github.com/dapr/js-sdk/runs/5754650900?check_suite_focus=true#step:3:10)27:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.apply (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:4821:27)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:4808:56), <anonymous>:1:16)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v4/dist/index.js:4809:[12](https://github.com/dapr/js-sdk/runs/5754650900?check_suite_focus=true#step:3:12))
```

**Comment by shubham1172** [comment]
Thanks @XavierGeerinck!
