### ISSUE TITLE
When the invoker experience 404 it throws empty error

### ISSUE THREAD

**Issue by avifatal** [dapr/js-sdk#296]
## Expected Behavior

The error needs to be more informative. its hard to detect on a large scale apps

## Actual Behavior

```
== APP == [Nest] 1585562  - 11/06/2022, 8:32:03   ERROR [ExceptionsHandler] ""
== APP == Error: ""
== APP ==     at HTTPClient.<anonymous> (/home/avi/work/tokenct/apps/api/node_modules/.pnpm/dapr-client@2.2.1/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:128:23)
== APP ==     at Generator.next (<anonymous>)
== APP ==     at fulfilled (/home/avi/work/tokenct/apps/api/node_modules/.pnpm/dapr-client@2.2.1/node_modules/dapr-client/implementation/Client/HTTPClient/HTTPClient.js:17:58)
== APP ==     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Steps to Reproduce the Problem

Just invoke an http call that is not answering on the other side

I think these lines should be more informative when throwing: https://github.com/dapr/js-sdk/blob/a5ae563deac37efef80ea3f801601a7cd8fa3837/src/implementation/Client/HTTPClient/HTTPClient.ts#L178

**Comment by salmankhan-prs** [comment]
Hi @shubham1172  can you help to understand what  we need to do ? 
I think we need add extra message when status is 404 ,500 ,502

**Comment by shubham1172** [comment]
> Hi @shubham1172 can you help to understand what we need to do ? I think we need add extra message when status is 404 ,500 ,502

Hi @salmankhan-prs, I think for starters we can respond with the status code and the error message, as proposed in the issue description,.
