### ISSUE TITLE
The "simple" example is not working - TypeError: event.setPubsubName is not a function

### ISSUE THREAD

**Issue by jasparmang** [dapr/js-sdk#52]
## Expected Behavior

The example is not working and running into an error.

## Actual Behavior

Executing the example results in an error:

`$ node app.js 
[...]/app.js:13
event.setPubsubName('pubsub');
      ^

TypeError: event.setPubsubName is not a function
    at Object.<anonymous> ([...]/js-sdk/examples/simple/app.js:13:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

## Steps to Reproduce the Problem

- Clone the repository
- go to ./examples/simple
- execute `npm install`
- start the sample by running `node app.js`
(the "main" entry in the package.json points to an index.js that does not exist)

**Comment by youngbupark** [comment]
I realized that the last publish of this npm pkg was 3 months ago. we will publish new version for 0.10.0 dapr runtime by tomorrow. sorry for your inconvenience.

**Comment by youngbupark** [comment]
0.6.0-preview01 npm pkg is released. please try it out.
